security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
    providers:
        users_in_memory: { memory: null }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # --- LE PLUS IMPORTANT EST ICI ---
        # On désactive la sécurité Symfony pour laisser passer
        # les requêtes vers l'API (on gère le token dans le Controller)
        api:
            pattern: ^/api
            security: false
        # ---------------------------------

        main:
            lazy: true
            provider: users_in_memory

    # Easy way to control access for large sections of your site
    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }